spring.application.name=SpringEx

# 1. ?????? ?? ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. DB ?? URL (??? ??? SpringDataJDBC ?? ? ?????!)
spring.datasource.url=jdbc:mysql://localhost:3306/mybatis

# 3. DB ??? ? ???? ????
spring.datasource.username=root
spring.datasource.password=1234